apiVersion: v2
name: basic-deployment
description: A Helm chart for deploying a basic application with Vault integration, optional ConfigMap and Ingress.
type: application
version: 0.1.0
appVersion: "1.0"
